vich_uploader:
    db_driver: orm

    mappings:
       vichFiles:
           uri_prefix: '/images/vichFiles'
           upload_destination: '%kernel.project_dir%/public/images/vichFiles'
           # namer: Vich\UploaderBundle\Naming\UniqidNamer
