<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEAsTfhI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEAsTfhI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEAsTfhI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEAsTfhI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEAsTfhI\App_KernelDevDebugContainer([
    'container.build_hash' => 'EAsTfhI',
    'container.build_id' => 'eee88844',
    'container.build_time' => 1605274182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEAsTfhI');
